FROM node:24-alpine

RUN apk add --no-cache bash git php83 php83-phar php83-openssl php83-mbstring php83-tokenizer php83-xml php83-ctype php83-pdo php83-pdo_pgsql php83-pgsql composer

WORKDIR /var/www/html
